using System.Text;

namespace Nitrogen.Grammar;

/// <summary>Writes one module's generated source: module class, kinds, views, visitor.</summary>
internal static class ModuleWriter
{
    public static string Write(EmitModel model, ModuleInfo info)
    {
        var module = info.Module;
        var helpers = new StringBuilder();
        var tokens = new TokenCodeWriter(model, info, helpers);
        var syntax = new SyntaxCodeWriter(model, info, tokens, helpers);
        var firstSets = new FirstSets(model);
        var rules = model.Analysis.PrimaryRules(module).ToList();
        var points = rules.OfType<ExtensibleRule>().ToList();
        var alternatives = info.Kinds.Where(k => k.Alternative is not null).ToList();
        string cls = info.ClassName;
        var semantics = new SemanticsWriter(model, info);
        bool hasSemantics = SemanticsWriter.HasSemantics(model, info);

        var b = new StringBuilder();
        b.Append("// <auto-generated/>\n")
            .Append($"// Generated by Nitrogen from syntax module {module.Name}. Do not edit.\n")
            .Append("#nullable enable\n")
            .Append("#pragma warning disable CS0164 // recovery labels (issue 235) are emitted for every element of a committed sequence\n\n")
            .Append(hasSemantics ? "using System;\nusing System.Collections.Generic;\nusing System.Linq;\nusing Nitrogen;\n\n" : "using System;\nusing Nitrogen;\n\n")
            .Append($"namespace {info.Namespace};\n\n")
            .Append($"public sealed unsafe class {cls} : SyntaxModule\n{{\n")
            .Append($"    public static readonly {cls} Instance = new();\n\n");

        foreach (var kind in info.Kinds) b.Append($"    public const int L{kind.Name} = {kind.Local};\n");
        if (info.Kinds.Count > 0) b.Append('\n');
        b.Append("    static readonly string[] s_names = { \"\"")
            .Append(string.Concat(info.Kinds.Select(k => ", " + CSharpText.Literal(k.Name))))
            .Append(" };\n\n");

        foreach (var point in points) b.Append($"    public readonly ExtensionPointDecl {CSharpText.Identifier(point.Name)};\n\n");
        b.Append($"    {cls}() : base({CSharpText.Literal(module.Name)})\n    {{\n");
        foreach (var point in points)
            b.Append($"        {CSharpText.Identifier(point.Name)} = new ExtensionPointDecl(this, {CSharpText.Literal(point.Name)});\n");
        b.Append("    }\n\n")
            .Append("    public static int Kind(int localKind) => Instance.KindBase | localKind;\n\n")
            .Append("    public override string GetKindName(int localKind) =>\n")
            .Append($"        localKind > 0 && localKind < s_names.Length ? s_names[localKind] : {CSharpText.Literal(module.Name + "#")} + localKind;\n\n");

        b.Append("    public override void Register(ExtensionRegistry registry)\n    {\n");
        foreach (var point in points) b.Append($"        registry.Declare({CSharpText.Identifier(point.Name)});\n");
        foreach (var kind in alternatives) b.Append("        ").Append(Registration(model, info, kind, firstSets)).Append('\n');
        b.Append("    }\n\n");

        foreach (var rule in rules.OfType<SyntaxRule>())
            b.Append($"    public static Rule {CSharpText.Identifier(rule.Name)} => new({CSharpText.Literal(rule.Name)}, &Parse{rule.Name});\n\n");

        b.Append("    public override Rule? GetRule(string name) => name switch\n    {\n");
        foreach (var rule in rules.OfType<SyntaxRule>())
            b.Append($"        {CSharpText.Literal(rule.Name)} => {CSharpText.Identifier(rule.Name)},\n");
        b.Append("        _ => null,\n    };\n\n");
        BindingWriter.Write(b, info);
        if (hasSemantics) semantics.WriteMembers(b);


        b.Append("    static bool Fail(ref ParserState s, scoped in ParseMark mark)\n    {\n        s.Reset(mark);\n        return false;\n    }\n\n");

        foreach (var rule in rules.OfType<TokenRule>()) tokens.WriteMatcher(b, rule);
        foreach (var rule in rules.OfType<SyntaxRule>()) syntax.WriteRule(b, rule);
        foreach (var kind in alternatives) syntax.WriteAlternative(b, kind);
        b.Append(helpers);

        var output = new StringBuilder(b.ToString().TrimEnd()).Append("\n}\n\n");

        output.Append($"public static class {info.KindsName}\n{{\n");
        foreach (var kind in info.Kinds)
            output.Append($"    public static readonly int {CSharpText.Identifier(kind.Name)} = {cls}.Kind({cls}.L{kind.Name});\n");
        output.Append("}\n\n");

        new ViewWriter(model, info).Write(output);
        if (hasSemantics) semantics.WriteTypes(output);
        return output.ToString().TrimEnd() + "\n";
    }

    static string Registration(EmitModel model, ModuleInfo info, KindInfo kind, FirstSets firstSets)
    {
        var alternative = kind.Alternative!;
        var point = kind.Point!;
        var pointInfo = model.Info(point.Module);
        string pointName = CSharpText.Identifier(point.Rule.Name);
        string pointRef = ReferenceEquals(pointInfo, info) ? pointName : $"{pointInfo.ClassPrefix(info)}Instance.{pointName}";
        bool postfix = model.Analysis.IsPostfix(alternative, info.Module, kind.ImplicitModule!, point.Key);
        var elements = SyntaxCodeWriter.Elements(alternative.Body);
        string first = firstSets.OfSequence(elements, postfix ? 1 : 0, info.Module, kind.ImplicitModule).ToAsciiSetCode();
        string kindRef = $"{info.KindsName}.{CSharpText.Identifier(kind.Name)}";
        string method = SyntaxCodeWriter.MethodName(kind);
        string name = CSharpText.Literal(alternative.Name);
        int precedence = alternative.Precedence ?? 0;
        if (!postfix)
            return $"registry.AddPrefix({pointRef}, new PrefixExtension({name}, {kindRef}, {precedence}, &{method}, {first}));";
        string associativity = alternative.Associativity == GrammarAssociativity.Right ? "Right" : "Left";
        return $"registry.AddPostfix({pointRef}, new PostfixExtension({name}, {kindRef}, {precedence}, Associativity.{associativity}, &{method}, {first}));";
    }
}
